workspace:
  base: /go
  path: .


pipeline:
  build:
    image: golang
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    commands:
      - go build -o /go/output/server
      - ./test.sh
      - docker build -t mwl/go-example-webserver .
